language: bg

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer          # word-level
- name: CountVectorsFeaturizer          # char-level за еднословни входове
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
- name: RegexEntityExtractor
  case_sensitive: false
  use_lookup_tables: true
  use_regexes: true
  use_word_boundaries: true
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: MemoizationPolicy
- name: TEDPolicy
  epochs: 50
assistant_id: 20250808-005748-flashed-mobile
